#!/bin/bash

# This is used to read in the version info from a JSON file
# It is called in the synth code build step commands after the version info is
# generated by a tooled called in a previous command
# The synth will export the version info file path for reading in here
# and this script reads form the file and exports the values to be available
# in the environemtn for the configuration files to absorb and
# pass into the constructs for APIs that require verison information.

# Read in the JSON file path
json_file=$VERSION_INFO_FILE_PATH
echo "json file name:"
echo $json_file
export GIT_TAG_NAME=$(jq -r '.tag_name' "$json_file")
export GIT_COMMIT_URL=$(jq -r '.commit_url' "$json_file")
export GIT_RELEASE_TITLE=$(jq -r '.release_title' "$json_file")
export GIT_RELEASE_URL=$(jq -r '.release_url' "$json_file")
