#!/bin/sh
# Generates .env for UI build with on-prem URLs. Call from UI dir.
# Usage: VITE_APP_BASE_URL=http://rrap1.it.csiro.au KEYCLOAK_REALM=provena ./scripts/ui-env-onprem.sh
# Default: http://localhost, realm provena
BASE="${VITE_APP_BASE_URL:-http://localhost}"
REALM="${VITE_KEYCLOAK_REALM:-provena}"
cat <<EOF
VITE_STAGE=DEV
VITE_DATA_STORE_API_ENDPOINT=${BASE}:8003
VITE_REGISTRY_API_ENDPOINT=${BASE}:8001
VITE_AUTH_API_ENDPOINT=${BASE}:8002
VITE_PROV_API_ENDPOINT=${BASE}:8007
VITE_JOB_API_ENDPOINT=${BASE}:8006
VITE_SEARCH_API_ENDPOINT=${BASE}:8004
VITE_WARMER_API_ENDPOINT=${BASE}:8004
VITE_LANDING_PAGE_LINK=${BASE}:3004
VITE_DATA_STORE_LINK=${BASE}:3002
VITE_PROV_STORE_LINK=${BASE}:3003
VITE_REGISTRY_LINK=${BASE}:3001
VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID:-landing-portal-ui}
VITE_KEYCLOAK_AUTH_ENDPOINT=${BASE}:8180
VITE_KEYCLOAK_REALM=${REALM}
VITE_DOCUMENTATION_BASE_LINK=https://docs.provena.io
VITE_CONTACT_US_LINK=
VITE_THEME_ID=
VITE_SENTRY_DSN=
VITE_GIT_COMMIT_ID=
VITE_MONITORING_ENABLED=false
VITE_FEATURE_NUMBER=
EOF
